import torch

config = {
    "seed": 42,
    "epochs": 5,
    "batch_size": 5,
    "max_length": 4096,
    "doc_stride": 512,
    "learning_rate": 3e-05,
    "max_grad_norm": 1.0,
    "weight_decay": 1e-2,
    "epsilon": 1e-8,
    "warmup_steps": 1000,
    "nlquad_num_training_examples": -1,
    "nlquad_num_validating_examples": -1,
    "nlquad_num_evaluation_examples": -1,
    "squad_v2": False,
    "squadv2_num_training_examples": -1,
    "squadv2_num_validating_examples": -1,
    "squadv2_num_evaluation_examples": -1,
    "gradient_accumulation_steps": 1,
    "print_freq": 10,
    "fp16": True,
    "push_to_hub": False,
    "train_path": "./data/NLQuAD_train.json",
    "valid_path": "./data/NLQuAD_valid.json",
    "eval_path": "./data/NLQuAD_eval.json",
    "output_dir": "./output",
    "pad_on_right": True,
    "hub_model_id": "sadaqabdo/XLMRobertaLongForQuestionAnswering-base-squad2-512-4096",
    "access_token": "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",
    "device": "cuda" if torch.cuda.is_available() else "cpu",
}
